### ISSUE TITLE
Error when folder contains a single wav file

### ISSUE THREAD

**Issue by lars76** [sarulab-speech/UTMOSv2#2]
### ☑️ Checks

- [X] I have searched [existing/past issues](https://github.com/sarulab-speech/UTMOSv2/issues) and found no similar issue.

### ✏️ Description

runner/_inference.py", line 35, in run_inference
    test_preds = np.concatenate(test_preds) if cfg.input_dir else np.array(test_preds)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-dimensional arrays cannot be concatenated

### Environment

Newest Python version.

### Expected behavior

No error.

### Steps to reproduce

1. Create a folder "t" containing a single wav file.
2. Run `python inference.py --input_dir t --out_path file.csv --predict_dataset somos`

**Comment by kAIto47802** [comment]
Thank you for reporting the bug. I'll fix it.
